export const ADDITEM = "ADDITEM";
export const REMOVEITEM = "REMOVEITEM";
export const PLACEORDER = "PLACEORDER";
export const GETLOCATION = "GETLOCATION";
export const GETLOCATIONSUCCESS = "GETLOCATIONSUCCESS";
export const GETLOCATIONFAILURE = "GETLOCATIONFAILURE";